version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspace
  fizzbuzz:
    container_name: "fizzbuzz"
    image: fizzbuzz:latest
    ports:
      - "5000:5000"